#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_IBW.DB_Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IBW_QA_23rd_Mar2020")]
	public partial class AdminExtensionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AdminExtensionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdminExtensionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminExtensionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminExtensionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminExtensionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCommonMasterData")]
		public ISingleResult<GetCommonMasterDataResult> GetCommonMasterData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetCommonMasterDataResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetCommonMasterDataResult
	{
		
		private string _vc_category_name;
		
		private System.Nullable<int> _int_associated_clients_count;
		
		private System.Nullable<int> _int_associated_config_questions_count;
		
		private long _int_common_master_data_id;
		
		private long _int_common_master_data_category_id;
		
		private string _vc_common_master_data_name;
		
		private System.Nullable<bool> _bt_valid;
		
		private System.Nullable<bool> _bt_delete;
		
		private System.Nullable<long> _int_created_by;
		
		private System.Nullable<System.DateTime> _dt_created_on;
		
		private System.Nullable<long> _int_modified_by;
		
		private System.Nullable<System.DateTime> _dt_modified_on;
		
		private System.Nullable<int> _dataTypeAssignedCount;
		
		public GetCommonMasterDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_category_name", DbType="VarChar(100)")]
		public string vc_category_name
		{
			get
			{
				return this._vc_category_name;
			}
			set
			{
				if ((this._vc_category_name != value))
				{
					this._vc_category_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_associated_clients_count", DbType="Int")]
		public System.Nullable<int> int_associated_clients_count
		{
			get
			{
				return this._int_associated_clients_count;
			}
			set
			{
				if ((this._int_associated_clients_count != value))
				{
					this._int_associated_clients_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_associated_config_questions_count", DbType="Int")]
		public System.Nullable<int> int_associated_config_questions_count
		{
			get
			{
				return this._int_associated_config_questions_count;
			}
			set
			{
				if ((this._int_associated_config_questions_count != value))
				{
					this._int_associated_config_questions_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_common_master_data_id", DbType="BigInt NOT NULL")]
		public long int_common_master_data_id
		{
			get
			{
				return this._int_common_master_data_id;
			}
			set
			{
				if ((this._int_common_master_data_id != value))
				{
					this._int_common_master_data_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_common_master_data_category_id", DbType="BigInt NOT NULL")]
		public long int_common_master_data_category_id
		{
			get
			{
				return this._int_common_master_data_category_id;
			}
			set
			{
				if ((this._int_common_master_data_category_id != value))
				{
					this._int_common_master_data_category_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_common_master_data_name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string vc_common_master_data_name
		{
			get
			{
				return this._vc_common_master_data_name;
			}
			set
			{
				if ((this._vc_common_master_data_name != value))
				{
					this._vc_common_master_data_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bt_valid", DbType="Bit")]
		public System.Nullable<bool> bt_valid
		{
			get
			{
				return this._bt_valid;
			}
			set
			{
				if ((this._bt_valid != value))
				{
					this._bt_valid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bt_delete", DbType="Bit")]
		public System.Nullable<bool> bt_delete
		{
			get
			{
				return this._bt_delete;
			}
			set
			{
				if ((this._bt_delete != value))
				{
					this._bt_delete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_created_by", DbType="BigInt")]
		public System.Nullable<long> int_created_by
		{
			get
			{
				return this._int_created_by;
			}
			set
			{
				if ((this._int_created_by != value))
				{
					this._int_created_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_created_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_created_on
		{
			get
			{
				return this._dt_created_on;
			}
			set
			{
				if ((this._dt_created_on != value))
				{
					this._dt_created_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_modified_by", DbType="BigInt")]
		public System.Nullable<long> int_modified_by
		{
			get
			{
				return this._int_modified_by;
			}
			set
			{
				if ((this._int_modified_by != value))
				{
					this._int_modified_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_modified_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_modified_on
		{
			get
			{
				return this._dt_modified_on;
			}
			set
			{
				if ((this._dt_modified_on != value))
				{
					this._dt_modified_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataTypeAssignedCount", DbType="Int")]
		public System.Nullable<int> dataTypeAssignedCount
		{
			get
			{
				return this._dataTypeAssignedCount;
			}
			set
			{
				if ((this._dataTypeAssignedCount != value))
				{
					this._dataTypeAssignedCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
