#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_IBW.DB_Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IBW_QA_23rd_Mar2020")]
	public partial class InvoicesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public InvoicesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InvoicesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoicesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoicesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoicesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_ibw_invoice_terms_and_condition> tbl_ibw_invoice_terms_and_conditions
		{
			get
			{
				return this.GetTable<tbl_ibw_invoice_terms_and_condition>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getcontactdetailsbyclientid")]
		public ISingleResult<getcontactdetailsbyclientidResult> getcontactdetailsbyclientid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_client_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_client_id);
			return ((ISingleResult<getcontactdetailsbyclientidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.generatelatestinvoicenumberbyquoteid")]
		public ISingleResult<generatelatestinvoicenumberbyquoteidResult> generatelatestinvoicenumberbyquoteid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_quote_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_quote_id);
			return ((ISingleResult<generatelatestinvoicenumberbyquoteidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getinvoiceclientdetailsbyclientid")]
		public ISingleResult<getinvoiceclientdetailsbyclientidResult> getinvoiceclientdetailsbyclientid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_client_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_client_id);
			return ((ISingleResult<getinvoiceclientdetailsbyclientidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateinvoicegoogledrivedetails")]
		public int updateinvoicegoogledrivedetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string vc_google_drive_file_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string vc_invoice_access_link)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_invoice_id, vc_google_drive_file_id, vc_invoice_access_link);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getinvoicepaymentdetails")]
		public ISingleResult<getinvoicepaymentdetailsResult> getinvoicepaymentdetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_invoice_id);
			return ((ISingleResult<getinvoicepaymentdetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateinvoicepaymentdetails")]
		public int updateinvoicepaymentdetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_payment_type_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(15,2)")] System.Nullable<decimal> dec_amount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string vc_comments, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_invoice_id, int_invoice_payment_type_id, dec_amount, vc_comments, int_user_id, result);
			result = ((System.Nullable<long>)(result1.GetParameterValue(5)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateinvoicepaymentdetailsattachmentinfo")]
		public int updateinvoicepaymentdetailsattachmentinfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_payment_details_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string vc_google_drive_file_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string vc_invoice_payment_details_attachment_access_link, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_invoice_payment_details_id, vc_google_drive_file_id, vc_invoice_payment_details_attachment_access_link, result);
			result = ((System.Nullable<long>)(result1.GetParameterValue(3)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getquoterelatedinvoicedetails")]
		public ISingleResult<getquoterelatedinvoicedetailsResult> getquoterelatedinvoicedetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_quote_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_quote_id, int_invoice_id);
			return ((ISingleResult<getquoterelatedinvoicedetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkinvoicenumberuniqueness")]
		public ISingleResult<checkinvoicenumberuniquenessResult> checkinvoicenumberuniqueness([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_quote_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(35)")] string vc_invoice_number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(35)")] string vc_manual_invoice_number)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_quote_id, int_invoice_id, vc_invoice_number, vc_manual_invoice_number);
			return ((ISingleResult<checkinvoicenumberuniquenessResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getinvoicefileids")]
		public ISingleResult<getinvoicefileidsResult> getinvoicefileids([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_invoice_id);
			return ((ISingleResult<getinvoicefileidsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatesentinvoicedetails")]
		public int updatesentinvoicedetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vc_sent_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vc_sent_to, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_invoice_id, vc_sent_by, vc_sent_to, int_user_id, result);
			result = ((System.Nullable<long>)(result1.GetParameterValue(4)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getinvoiceitemdetails")]
		public ISingleResult<getinvoiceitemdetailsResult> getinvoiceitemdetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_quote_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_quote_id);
			return ((ISingleResult<getinvoiceitemdetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getinvoicefeedetails")]
		public ISingleResult<getinvoicefeedetailsResult> getinvoicefeedetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_invoice_id);
			return ((ISingleResult<getinvoicefeedetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getinvoicedetailsbyinvoiceid")]
		public ISingleResult<getinvoicedetailsbyinvoiceidResult> getinvoicedetailsbyinvoiceid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> int_invoice_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), int_invoice_id);
			return ((ISingleResult<getinvoicedetailsbyinvoiceidResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ibw_invoice_terms_and_conditions")]
	public partial class tbl_ibw_invoice_terms_and_condition
	{
		
		private string _vc_terms_and_conditions;
		
		private long _int_last_modified_by;
		
		private System.DateTime _dt_last_modified_date;
		
		public tbl_ibw_invoice_terms_and_condition()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_terms_and_conditions", DbType="VarChar(1000)")]
		public string vc_terms_and_conditions
		{
			get
			{
				return this._vc_terms_and_conditions;
			}
			set
			{
				if ((this._vc_terms_and_conditions != value))
				{
					this._vc_terms_and_conditions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_last_modified_by", DbType="BigInt NOT NULL")]
		public long int_last_modified_by
		{
			get
			{
				return this._int_last_modified_by;
			}
			set
			{
				if ((this._int_last_modified_by != value))
				{
					this._int_last_modified_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_last_modified_date", DbType="DateTime NOT NULL")]
		public System.DateTime dt_last_modified_date
		{
			get
			{
				return this._dt_last_modified_date;
			}
			set
			{
				if ((this._dt_last_modified_date != value))
				{
					this._dt_last_modified_date = value;
				}
			}
		}
	}
	
	public partial class getcontactdetailsbyclientidResult
	{
		
		private long _int_contact_id;
		
		private string _vc_contact_name;
		
		private string _vc_job_title;
		
		private string _vc_contact_email;
		
		private string _vc_contact_phone_number;
		
		public getcontactdetailsbyclientidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_contact_id", DbType="BigInt NOT NULL")]
		public long int_contact_id
		{
			get
			{
				return this._int_contact_id;
			}
			set
			{
				if ((this._int_contact_id != value))
				{
					this._int_contact_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_contact_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string vc_contact_name
		{
			get
			{
				return this._vc_contact_name;
			}
			set
			{
				if ((this._vc_contact_name != value))
				{
					this._vc_contact_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_job_title", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string vc_job_title
		{
			get
			{
				return this._vc_job_title;
			}
			set
			{
				if ((this._vc_job_title != value))
				{
					this._vc_job_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_contact_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string vc_contact_email
		{
			get
			{
				return this._vc_contact_email;
			}
			set
			{
				if ((this._vc_contact_email != value))
				{
					this._vc_contact_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_contact_phone_number", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string vc_contact_phone_number
		{
			get
			{
				return this._vc_contact_phone_number;
			}
			set
			{
				if ((this._vc_contact_phone_number != value))
				{
					this._vc_contact_phone_number = value;
				}
			}
		}
	}
	
	public partial class generatelatestinvoicenumberbyquoteidResult
	{
		
		private string _vc_invoice_number;
		
		public generatelatestinvoicenumberbyquoteidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_number", DbType="VarChar(22)")]
		public string vc_invoice_number
		{
			get
			{
				return this._vc_invoice_number;
			}
			set
			{
				if ((this._vc_invoice_number != value))
				{
					this._vc_invoice_number = value;
				}
			}
		}
	}
	
	public partial class getinvoiceclientdetailsbyclientidResult
	{
		
		private string _vc_client_name;
		
		private string _vc_client_email;
		
		private string _vc_client_phone_number;
		
		private string _vc_Country_Name;
		
		private string _vc_State_Name;
		
		private string _vc_city;
		
		private string _vc_zip_or_postal;
		
		private string _vc_site_street_address;
		
		public getinvoiceclientdetailsbyclientidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_client_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string vc_client_name
		{
			get
			{
				return this._vc_client_name;
			}
			set
			{
				if ((this._vc_client_name != value))
				{
					this._vc_client_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_client_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string vc_client_email
		{
			get
			{
				return this._vc_client_email;
			}
			set
			{
				if ((this._vc_client_email != value))
				{
					this._vc_client_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_client_phone_number", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string vc_client_phone_number
		{
			get
			{
				return this._vc_client_phone_number;
			}
			set
			{
				if ((this._vc_client_phone_number != value))
				{
					this._vc_client_phone_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_Country_Name", DbType="VarChar(100)")]
		public string vc_Country_Name
		{
			get
			{
				return this._vc_Country_Name;
			}
			set
			{
				if ((this._vc_Country_Name != value))
				{
					this._vc_Country_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_State_Name", DbType="VarChar(100)")]
		public string vc_State_Name
		{
			get
			{
				return this._vc_State_Name;
			}
			set
			{
				if ((this._vc_State_Name != value))
				{
					this._vc_State_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_city", DbType="VarChar(100)")]
		public string vc_city
		{
			get
			{
				return this._vc_city;
			}
			set
			{
				if ((this._vc_city != value))
				{
					this._vc_city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_zip_or_postal", DbType="NVarChar(100)")]
		public string vc_zip_or_postal
		{
			get
			{
				return this._vc_zip_or_postal;
			}
			set
			{
				if ((this._vc_zip_or_postal != value))
				{
					this._vc_zip_or_postal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_site_street_address", DbType="VarChar(100)")]
		public string vc_site_street_address
		{
			get
			{
				return this._vc_site_street_address;
			}
			set
			{
				if ((this._vc_site_street_address != value))
				{
					this._vc_site_street_address = value;
				}
			}
		}
	}
	
	public partial class getinvoicepaymentdetailsResult
	{
		
		private long _int_payment_type_id;
		
		private string _payment_type;
		
		private decimal _dec_amount;
		
		private string _vc_comments;
		
		private long _int_created_by;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _dt_created_on;
		
		private string _vc_google_drive_file_id;
		
		private string _vc_invoice_payment_details_attachment_access_link;
		
		public getinvoicepaymentdetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_payment_type_id", DbType="BigInt NOT NULL")]
		public long int_payment_type_id
		{
			get
			{
				return this._int_payment_type_id;
			}
			set
			{
				if ((this._int_payment_type_id != value))
				{
					this._int_payment_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_type", DbType="VarChar(100)")]
		public string payment_type
		{
			get
			{
				return this._payment_type;
			}
			set
			{
				if ((this._payment_type != value))
				{
					this._payment_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_amount", DbType="Decimal(15,2) NOT NULL")]
		public decimal dec_amount
		{
			get
			{
				return this._dec_amount;
			}
			set
			{
				if ((this._dec_amount != value))
				{
					this._dec_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_comments", DbType="VarChar(1000)")]
		public string vc_comments
		{
			get
			{
				return this._vc_comments;
			}
			set
			{
				if ((this._vc_comments != value))
				{
					this._vc_comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_created_by", DbType="BigInt NOT NULL")]
		public long int_created_by
		{
			get
			{
				return this._int_created_by;
			}
			set
			{
				if ((this._int_created_by != value))
				{
					this._int_created_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(201)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this._created_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_created_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_created_on
		{
			get
			{
				return this._dt_created_on;
			}
			set
			{
				if ((this._dt_created_on != value))
				{
					this._dt_created_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_google_drive_file_id", DbType="VarChar(MAX)")]
		public string vc_google_drive_file_id
		{
			get
			{
				return this._vc_google_drive_file_id;
			}
			set
			{
				if ((this._vc_google_drive_file_id != value))
				{
					this._vc_google_drive_file_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_payment_details_attachment_access_link", DbType="VarChar(MAX)")]
		public string vc_invoice_payment_details_attachment_access_link
		{
			get
			{
				return this._vc_invoice_payment_details_attachment_access_link;
			}
			set
			{
				if ((this._vc_invoice_payment_details_attachment_access_link != value))
				{
					this._vc_invoice_payment_details_attachment_access_link = value;
				}
			}
		}
	}
	
	public partial class getquoterelatedinvoicedetailsResult
	{
		
		private System.Nullable<long> _int_quote_id;
		
		private System.Nullable<long> _int_site_id;
		
		private string _vc_site_name;
		
		private System.Nullable<long> _int_sow_id;
		
		private string _vc_sow_name;
		
		private System.Nullable<long> _int_manage_sow_id;
		
		private System.Nullable<long> _int_sow_invoice_type_id;
		
		private string _vc_fee_structure;
		
		private System.Nullable<long> _int_task_id;
		
		private string _vc_task_name;
		
		private System.Nullable<long> _int_action_log_hour_id;
		
		private System.Nullable<long> _int_action_expense_id;
		
		private System.Nullable<long> _int_timesheet_id;
		
		private System.Nullable<long> _int_expense_id;
		
		private System.Nullable<long> _int_budget_sow_id;
		
		private System.Nullable<long> _int_action_id;
		
		private string _vc_action_name;
		
		private System.Nullable<long> _int_job_code_id;
		
		private string _vc_job_code;
		
		private string _vc_job_title;
		
		private string _vc_expense_code;
		
		private System.Nullable<decimal> _dec_worked_hours;
		
		private System.Nullable<decimal> _total;
		
		private System.Nullable<decimal> _expenses;
		
		private System.Nullable<decimal> _budget_total;
		
		private System.Nullable<decimal> _quoted_total;
		
		private string _vc_user_name;
		
		private System.Nullable<System.DateTime> _dt_date;
		
		private decimal _invoiced_percent;
		
		private decimal _dec_remaining_unbilled;
		
		private decimal _dec_billed;
		
		private System.Nullable<long> _int_invoice_item_id;
		
		public getquoterelatedinvoicedetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_quote_id", DbType="BigInt")]
		public System.Nullable<long> int_quote_id
		{
			get
			{
				return this._int_quote_id;
			}
			set
			{
				if ((this._int_quote_id != value))
				{
					this._int_quote_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_site_id", DbType="BigInt")]
		public System.Nullable<long> int_site_id
		{
			get
			{
				return this._int_site_id;
			}
			set
			{
				if ((this._int_site_id != value))
				{
					this._int_site_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_site_name", DbType="VarChar(100)")]
		public string vc_site_name
		{
			get
			{
				return this._vc_site_name;
			}
			set
			{
				if ((this._vc_site_name != value))
				{
					this._vc_site_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_sow_id", DbType="BigInt")]
		public System.Nullable<long> int_sow_id
		{
			get
			{
				return this._int_sow_id;
			}
			set
			{
				if ((this._int_sow_id != value))
				{
					this._int_sow_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_sow_name", DbType="VarChar(100)")]
		public string vc_sow_name
		{
			get
			{
				return this._vc_sow_name;
			}
			set
			{
				if ((this._vc_sow_name != value))
				{
					this._vc_sow_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_manage_sow_id", DbType="BigInt")]
		public System.Nullable<long> int_manage_sow_id
		{
			get
			{
				return this._int_manage_sow_id;
			}
			set
			{
				if ((this._int_manage_sow_id != value))
				{
					this._int_manage_sow_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_sow_invoice_type_id", DbType="BigInt")]
		public System.Nullable<long> int_sow_invoice_type_id
		{
			get
			{
				return this._int_sow_invoice_type_id;
			}
			set
			{
				if ((this._int_sow_invoice_type_id != value))
				{
					this._int_sow_invoice_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_fee_structure", DbType="VarChar(100)")]
		public string vc_fee_structure
		{
			get
			{
				return this._vc_fee_structure;
			}
			set
			{
				if ((this._vc_fee_structure != value))
				{
					this._vc_fee_structure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_task_id", DbType="BigInt")]
		public System.Nullable<long> int_task_id
		{
			get
			{
				return this._int_task_id;
			}
			set
			{
				if ((this._int_task_id != value))
				{
					this._int_task_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_task_name", DbType="NVarChar(500)")]
		public string vc_task_name
		{
			get
			{
				return this._vc_task_name;
			}
			set
			{
				if ((this._vc_task_name != value))
				{
					this._vc_task_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_action_log_hour_id", DbType="BigInt")]
		public System.Nullable<long> int_action_log_hour_id
		{
			get
			{
				return this._int_action_log_hour_id;
			}
			set
			{
				if ((this._int_action_log_hour_id != value))
				{
					this._int_action_log_hour_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_action_expense_id", DbType="BigInt")]
		public System.Nullable<long> int_action_expense_id
		{
			get
			{
				return this._int_action_expense_id;
			}
			set
			{
				if ((this._int_action_expense_id != value))
				{
					this._int_action_expense_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_timesheet_id", DbType="BigInt")]
		public System.Nullable<long> int_timesheet_id
		{
			get
			{
				return this._int_timesheet_id;
			}
			set
			{
				if ((this._int_timesheet_id != value))
				{
					this._int_timesheet_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_expense_id", DbType="BigInt")]
		public System.Nullable<long> int_expense_id
		{
			get
			{
				return this._int_expense_id;
			}
			set
			{
				if ((this._int_expense_id != value))
				{
					this._int_expense_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_budget_sow_id", DbType="BigInt")]
		public System.Nullable<long> int_budget_sow_id
		{
			get
			{
				return this._int_budget_sow_id;
			}
			set
			{
				if ((this._int_budget_sow_id != value))
				{
					this._int_budget_sow_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_action_id", DbType="BigInt")]
		public System.Nullable<long> int_action_id
		{
			get
			{
				return this._int_action_id;
			}
			set
			{
				if ((this._int_action_id != value))
				{
					this._int_action_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_action_name", DbType="NVarChar(200)")]
		public string vc_action_name
		{
			get
			{
				return this._vc_action_name;
			}
			set
			{
				if ((this._vc_action_name != value))
				{
					this._vc_action_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_job_code_id", DbType="BigInt")]
		public System.Nullable<long> int_job_code_id
		{
			get
			{
				return this._int_job_code_id;
			}
			set
			{
				if ((this._int_job_code_id != value))
				{
					this._int_job_code_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_job_code", DbType="VarChar(100)")]
		public string vc_job_code
		{
			get
			{
				return this._vc_job_code;
			}
			set
			{
				if ((this._vc_job_code != value))
				{
					this._vc_job_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_job_title", DbType="VarChar(100)")]
		public string vc_job_title
		{
			get
			{
				return this._vc_job_title;
			}
			set
			{
				if ((this._vc_job_title != value))
				{
					this._vc_job_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_expense_code", DbType="VarChar(100)")]
		public string vc_expense_code
		{
			get
			{
				return this._vc_expense_code;
			}
			set
			{
				if ((this._vc_expense_code != value))
				{
					this._vc_expense_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_worked_hours", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> dec_worked_hours
		{
			get
			{
				return this._dec_worked_hours;
			}
			set
			{
				if ((this._dec_worked_hours != value))
				{
					this._dec_worked_hours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(37,4)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expenses", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> expenses
		{
			get
			{
				return this._expenses;
			}
			set
			{
				if ((this._expenses != value))
				{
					this._expenses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budget_total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> budget_total
		{
			get
			{
				return this._budget_total;
			}
			set
			{
				if ((this._budget_total != value))
				{
					this._budget_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quoted_total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> quoted_total
		{
			get
			{
				return this._quoted_total;
			}
			set
			{
				if ((this._quoted_total != value))
				{
					this._quoted_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_user_name", DbType="VarChar(201)")]
		public string vc_user_name
		{
			get
			{
				return this._vc_user_name;
			}
			set
			{
				if ((this._vc_user_name != value))
				{
					this._vc_user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_date
		{
			get
			{
				return this._dt_date;
			}
			set
			{
				if ((this._dt_date != value))
				{
					this._dt_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiced_percent", DbType="Decimal(38,2) NOT NULL")]
		public decimal invoiced_percent
		{
			get
			{
				return this._invoiced_percent;
			}
			set
			{
				if ((this._invoiced_percent != value))
				{
					this._invoiced_percent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_remaining_unbilled", DbType="Decimal(38,2) NOT NULL")]
		public decimal dec_remaining_unbilled
		{
			get
			{
				return this._dec_remaining_unbilled;
			}
			set
			{
				if ((this._dec_remaining_unbilled != value))
				{
					this._dec_remaining_unbilled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_billed", DbType="Decimal(15,2) NOT NULL")]
		public decimal dec_billed
		{
			get
			{
				return this._dec_billed;
			}
			set
			{
				if ((this._dec_billed != value))
				{
					this._dec_billed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_invoice_item_id", DbType="BigInt")]
		public System.Nullable<long> int_invoice_item_id
		{
			get
			{
				return this._int_invoice_item_id;
			}
			set
			{
				if ((this._int_invoice_item_id != value))
				{
					this._int_invoice_item_id = value;
				}
			}
		}
	}
	
	public partial class checkinvoicenumberuniquenessResult
	{
		
		private string _message;
		
		public checkinvoicenumberuniquenessResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(200)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this._message = value;
				}
			}
		}
	}
	
	public partial class getinvoicefileidsResult
	{
		
		private string _vc_file_id;
		
		public getinvoicefileidsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_file_id", DbType="VarChar(MAX)")]
		public string vc_file_id
		{
			get
			{
				return this._vc_file_id;
			}
			set
			{
				if ((this._vc_file_id != value))
				{
					this._vc_file_id = value;
				}
			}
		}
	}
	
	public partial class getinvoiceitemdetailsResult
	{
		
		private long _int_invoice_id;
		
		private string _vc_google_drive_file_id;
		
		private string _vc_invoice_access_link;
		
		private System.Nullable<decimal> _dec_HST_percent;
		
		private long _int_invoice_item_id;
		
		private string _vc_invoice_number;
		
		private string _vc_manual_invoice_number;
		
		private System.Nullable<decimal> _dec_invoice_total;
		
		private string _vc_sent_by;
		
		private string _vc_sent_to;
		
		private System.Nullable<System.DateTime> _dt_sent_date;
		
		private string _vc_invoice_status;
		
		private System.Nullable<decimal> _dec_balance_amount;
		
		private System.Nullable<System.DateTime> _dt_invoice_date;
		
		private System.Nullable<int> _int_days_old;
		
		private decimal _dec_invoiced_percent;
		
		private decimal _dec_invoiced_total;
		
		private decimal _dec_invoiced_percent1;
		
		private System.Nullable<long> _int_quote_id;
		
		private System.Nullable<long> _int_site_id;
		
		private string _vc_site_name;
		
		private System.Nullable<long> _int_sow_id;
		
		private string _vc_sow_name;
		
		private System.Nullable<long> _int_manage_sow_id;
		
		private System.Nullable<long> _int_sow_invoice_type_id;
		
		private string _vc_fee_structure;
		
		private System.Nullable<long> _int_task_id;
		
		private string _vc_task_name;
		
		private System.Nullable<long> _int_action_log_hour_id;
		
		private System.Nullable<long> _int_action_expense_id;
		
		private System.Nullable<long> _int_timesheet_id;
		
		private System.Nullable<long> _int_expense_id;
		
		private System.Nullable<long> _int_budget_sow_id;
		
		private System.Nullable<long> _int_action_id;
		
		private string _vc_action_name;
		
		private System.Nullable<long> _int_job_code_id;
		
		private string _vc_job_code;
		
		private string _vc_job_title;
		
		private string _vc_expense_code;
		
		private System.Nullable<decimal> _dec_worked_hours;
		
		private System.Nullable<decimal> _total;
		
		private System.Nullable<decimal> _expenses;
		
		private System.Nullable<decimal> _quoted_total;
		
		public getinvoiceitemdetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_invoice_id", DbType="BigInt NOT NULL")]
		public long int_invoice_id
		{
			get
			{
				return this._int_invoice_id;
			}
			set
			{
				if ((this._int_invoice_id != value))
				{
					this._int_invoice_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_google_drive_file_id", DbType="VarChar(MAX)")]
		public string vc_google_drive_file_id
		{
			get
			{
				return this._vc_google_drive_file_id;
			}
			set
			{
				if ((this._vc_google_drive_file_id != value))
				{
					this._vc_google_drive_file_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_access_link", DbType="VarChar(MAX)")]
		public string vc_invoice_access_link
		{
			get
			{
				return this._vc_invoice_access_link;
			}
			set
			{
				if ((this._vc_invoice_access_link != value))
				{
					this._vc_invoice_access_link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_HST_percent", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> dec_HST_percent
		{
			get
			{
				return this._dec_HST_percent;
			}
			set
			{
				if ((this._dec_HST_percent != value))
				{
					this._dec_HST_percent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_invoice_item_id", DbType="BigInt NOT NULL")]
		public long int_invoice_item_id
		{
			get
			{
				return this._int_invoice_item_id;
			}
			set
			{
				if ((this._int_invoice_item_id != value))
				{
					this._int_invoice_item_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_number", DbType="VarChar(25)")]
		public string vc_invoice_number
		{
			get
			{
				return this._vc_invoice_number;
			}
			set
			{
				if ((this._vc_invoice_number != value))
				{
					this._vc_invoice_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_manual_invoice_number", DbType="VarChar(25)")]
		public string vc_manual_invoice_number
		{
			get
			{
				return this._vc_manual_invoice_number;
			}
			set
			{
				if ((this._vc_manual_invoice_number != value))
				{
					this._vc_manual_invoice_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_invoice_total", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> dec_invoice_total
		{
			get
			{
				return this._dec_invoice_total;
			}
			set
			{
				if ((this._dec_invoice_total != value))
				{
					this._dec_invoice_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_sent_by", DbType="VarChar(100)")]
		public string vc_sent_by
		{
			get
			{
				return this._vc_sent_by;
			}
			set
			{
				if ((this._vc_sent_by != value))
				{
					this._vc_sent_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_sent_to", DbType="VarChar(100)")]
		public string vc_sent_to
		{
			get
			{
				return this._vc_sent_to;
			}
			set
			{
				if ((this._vc_sent_to != value))
				{
					this._vc_sent_to = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_sent_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_sent_date
		{
			get
			{
				return this._dt_sent_date;
			}
			set
			{
				if ((this._dt_sent_date != value))
				{
					this._dt_sent_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_status", DbType="VarChar(100)")]
		public string vc_invoice_status
		{
			get
			{
				return this._vc_invoice_status;
			}
			set
			{
				if ((this._vc_invoice_status != value))
				{
					this._vc_invoice_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_balance_amount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> dec_balance_amount
		{
			get
			{
				return this._dec_balance_amount;
			}
			set
			{
				if ((this._dec_balance_amount != value))
				{
					this._dec_balance_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_invoice_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_invoice_date
		{
			get
			{
				return this._dt_invoice_date;
			}
			set
			{
				if ((this._dt_invoice_date != value))
				{
					this._dt_invoice_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_days_old", DbType="Int")]
		public System.Nullable<int> int_days_old
		{
			get
			{
				return this._int_days_old;
			}
			set
			{
				if ((this._int_days_old != value))
				{
					this._int_days_old = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_invoiced_percent", DbType="Decimal(5,2) NOT NULL")]
		public decimal dec_invoiced_percent
		{
			get
			{
				return this._dec_invoiced_percent;
			}
			set
			{
				if ((this._dec_invoiced_percent != value))
				{
					this._dec_invoiced_percent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_invoiced_total", DbType="Decimal(15,2) NOT NULL")]
		public decimal dec_invoiced_total
		{
			get
			{
				return this._dec_invoiced_total;
			}
			set
			{
				if ((this._dec_invoiced_total != value))
				{
					this._dec_invoiced_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_invoiced_percent1", DbType="Decimal(5,2) NOT NULL")]
		public decimal dec_invoiced_percent1
		{
			get
			{
				return this._dec_invoiced_percent1;
			}
			set
			{
				if ((this._dec_invoiced_percent1 != value))
				{
					this._dec_invoiced_percent1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_quote_id", DbType="BigInt")]
		public System.Nullable<long> int_quote_id
		{
			get
			{
				return this._int_quote_id;
			}
			set
			{
				if ((this._int_quote_id != value))
				{
					this._int_quote_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_site_id", DbType="BigInt")]
		public System.Nullable<long> int_site_id
		{
			get
			{
				return this._int_site_id;
			}
			set
			{
				if ((this._int_site_id != value))
				{
					this._int_site_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_site_name", DbType="VarChar(100)")]
		public string vc_site_name
		{
			get
			{
				return this._vc_site_name;
			}
			set
			{
				if ((this._vc_site_name != value))
				{
					this._vc_site_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_sow_id", DbType="BigInt")]
		public System.Nullable<long> int_sow_id
		{
			get
			{
				return this._int_sow_id;
			}
			set
			{
				if ((this._int_sow_id != value))
				{
					this._int_sow_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_sow_name", DbType="VarChar(100)")]
		public string vc_sow_name
		{
			get
			{
				return this._vc_sow_name;
			}
			set
			{
				if ((this._vc_sow_name != value))
				{
					this._vc_sow_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_manage_sow_id", DbType="BigInt")]
		public System.Nullable<long> int_manage_sow_id
		{
			get
			{
				return this._int_manage_sow_id;
			}
			set
			{
				if ((this._int_manage_sow_id != value))
				{
					this._int_manage_sow_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_sow_invoice_type_id", DbType="BigInt")]
		public System.Nullable<long> int_sow_invoice_type_id
		{
			get
			{
				return this._int_sow_invoice_type_id;
			}
			set
			{
				if ((this._int_sow_invoice_type_id != value))
				{
					this._int_sow_invoice_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_fee_structure", DbType="VarChar(100)")]
		public string vc_fee_structure
		{
			get
			{
				return this._vc_fee_structure;
			}
			set
			{
				if ((this._vc_fee_structure != value))
				{
					this._vc_fee_structure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_task_id", DbType="BigInt")]
		public System.Nullable<long> int_task_id
		{
			get
			{
				return this._int_task_id;
			}
			set
			{
				if ((this._int_task_id != value))
				{
					this._int_task_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_task_name", DbType="NVarChar(500)")]
		public string vc_task_name
		{
			get
			{
				return this._vc_task_name;
			}
			set
			{
				if ((this._vc_task_name != value))
				{
					this._vc_task_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_action_log_hour_id", DbType="BigInt")]
		public System.Nullable<long> int_action_log_hour_id
		{
			get
			{
				return this._int_action_log_hour_id;
			}
			set
			{
				if ((this._int_action_log_hour_id != value))
				{
					this._int_action_log_hour_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_action_expense_id", DbType="BigInt")]
		public System.Nullable<long> int_action_expense_id
		{
			get
			{
				return this._int_action_expense_id;
			}
			set
			{
				if ((this._int_action_expense_id != value))
				{
					this._int_action_expense_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_timesheet_id", DbType="BigInt")]
		public System.Nullable<long> int_timesheet_id
		{
			get
			{
				return this._int_timesheet_id;
			}
			set
			{
				if ((this._int_timesheet_id != value))
				{
					this._int_timesheet_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_expense_id", DbType="BigInt")]
		public System.Nullable<long> int_expense_id
		{
			get
			{
				return this._int_expense_id;
			}
			set
			{
				if ((this._int_expense_id != value))
				{
					this._int_expense_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_budget_sow_id", DbType="BigInt")]
		public System.Nullable<long> int_budget_sow_id
		{
			get
			{
				return this._int_budget_sow_id;
			}
			set
			{
				if ((this._int_budget_sow_id != value))
				{
					this._int_budget_sow_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_action_id", DbType="BigInt")]
		public System.Nullable<long> int_action_id
		{
			get
			{
				return this._int_action_id;
			}
			set
			{
				if ((this._int_action_id != value))
				{
					this._int_action_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_action_name", DbType="NVarChar(200)")]
		public string vc_action_name
		{
			get
			{
				return this._vc_action_name;
			}
			set
			{
				if ((this._vc_action_name != value))
				{
					this._vc_action_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_job_code_id", DbType="BigInt")]
		public System.Nullable<long> int_job_code_id
		{
			get
			{
				return this._int_job_code_id;
			}
			set
			{
				if ((this._int_job_code_id != value))
				{
					this._int_job_code_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_job_code", DbType="VarChar(100)")]
		public string vc_job_code
		{
			get
			{
				return this._vc_job_code;
			}
			set
			{
				if ((this._vc_job_code != value))
				{
					this._vc_job_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_job_title", DbType="VarChar(100)")]
		public string vc_job_title
		{
			get
			{
				return this._vc_job_title;
			}
			set
			{
				if ((this._vc_job_title != value))
				{
					this._vc_job_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_expense_code", DbType="VarChar(100)")]
		public string vc_expense_code
		{
			get
			{
				return this._vc_expense_code;
			}
			set
			{
				if ((this._vc_expense_code != value))
				{
					this._vc_expense_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_worked_hours", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> dec_worked_hours
		{
			get
			{
				return this._dec_worked_hours;
			}
			set
			{
				if ((this._dec_worked_hours != value))
				{
					this._dec_worked_hours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(37,4)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expenses", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> expenses
		{
			get
			{
				return this._expenses;
			}
			set
			{
				if ((this._expenses != value))
				{
					this._expenses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quoted_total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> quoted_total
		{
			get
			{
				return this._quoted_total;
			}
			set
			{
				if ((this._quoted_total != value))
				{
					this._quoted_total = value;
				}
			}
		}
	}
	
	public partial class getinvoicefeedetailsResult
	{
		
		private System.Nullable<long> _int_site_id;
		
		private System.Nullable<long> _int_sow_id;
		
		private string _vc_site_name;
		
		private string _vc_sow_name;
		
		private string _vc_fee_structure;
		
		private decimal _dec_invoice_total;
		
		private System.DateTime _dt_created_date;
		
		private long _int_quote_id;
		
		private string _vc_contact_name;
		
		private System.Nullable<long> _int_client_id;
		
		private string _vc_description;
		
		private System.Nullable<decimal> _dec_HST_percent;
		
		private string _vc_invoice_number;
		
		private string _vc_purchase_order_number;
		
		private string _vc_manual_invoice_number;
		
		private System.Nullable<decimal> _dec_invoiced_total;
		
		private System.Nullable<decimal> _dec_balance_amount;
		
		public getinvoicefeedetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_site_id", DbType="BigInt")]
		public System.Nullable<long> int_site_id
		{
			get
			{
				return this._int_site_id;
			}
			set
			{
				if ((this._int_site_id != value))
				{
					this._int_site_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_sow_id", DbType="BigInt")]
		public System.Nullable<long> int_sow_id
		{
			get
			{
				return this._int_sow_id;
			}
			set
			{
				if ((this._int_sow_id != value))
				{
					this._int_sow_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_site_name", DbType="VarChar(100)")]
		public string vc_site_name
		{
			get
			{
				return this._vc_site_name;
			}
			set
			{
				if ((this._vc_site_name != value))
				{
					this._vc_site_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_sow_name", DbType="VarChar(100)")]
		public string vc_sow_name
		{
			get
			{
				return this._vc_sow_name;
			}
			set
			{
				if ((this._vc_sow_name != value))
				{
					this._vc_sow_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_fee_structure", DbType="VarChar(100)")]
		public string vc_fee_structure
		{
			get
			{
				return this._vc_fee_structure;
			}
			set
			{
				if ((this._vc_fee_structure != value))
				{
					this._vc_fee_structure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_invoice_total", DbType="Decimal(15,2) NOT NULL")]
		public decimal dec_invoice_total
		{
			get
			{
				return this._dec_invoice_total;
			}
			set
			{
				if ((this._dec_invoice_total != value))
				{
					this._dec_invoice_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_created_date", DbType="DateTime NOT NULL")]
		public System.DateTime dt_created_date
		{
			get
			{
				return this._dt_created_date;
			}
			set
			{
				if ((this._dt_created_date != value))
				{
					this._dt_created_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_quote_id", DbType="BigInt NOT NULL")]
		public long int_quote_id
		{
			get
			{
				return this._int_quote_id;
			}
			set
			{
				if ((this._int_quote_id != value))
				{
					this._int_quote_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_contact_name", DbType="VarChar(100)")]
		public string vc_contact_name
		{
			get
			{
				return this._vc_contact_name;
			}
			set
			{
				if ((this._vc_contact_name != value))
				{
					this._vc_contact_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_client_id", DbType="BigInt")]
		public System.Nullable<long> int_client_id
		{
			get
			{
				return this._int_client_id;
			}
			set
			{
				if ((this._int_client_id != value))
				{
					this._int_client_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_description", DbType="VarChar(1000)")]
		public string vc_description
		{
			get
			{
				return this._vc_description;
			}
			set
			{
				if ((this._vc_description != value))
				{
					this._vc_description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_HST_percent", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> dec_HST_percent
		{
			get
			{
				return this._dec_HST_percent;
			}
			set
			{
				if ((this._dec_HST_percent != value))
				{
					this._dec_HST_percent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_number", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string vc_invoice_number
		{
			get
			{
				return this._vc_invoice_number;
			}
			set
			{
				if ((this._vc_invoice_number != value))
				{
					this._vc_invoice_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_purchase_order_number", DbType="VarChar(25)")]
		public string vc_purchase_order_number
		{
			get
			{
				return this._vc_purchase_order_number;
			}
			set
			{
				if ((this._vc_purchase_order_number != value))
				{
					this._vc_purchase_order_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_manual_invoice_number", DbType="VarChar(25)")]
		public string vc_manual_invoice_number
		{
			get
			{
				return this._vc_manual_invoice_number;
			}
			set
			{
				if ((this._vc_manual_invoice_number != value))
				{
					this._vc_manual_invoice_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_invoiced_total", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> dec_invoiced_total
		{
			get
			{
				return this._dec_invoiced_total;
			}
			set
			{
				if ((this._dec_invoiced_total != value))
				{
					this._dec_invoiced_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_balance_amount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> dec_balance_amount
		{
			get
			{
				return this._dec_balance_amount;
			}
			set
			{
				if ((this._dec_balance_amount != value))
				{
					this._dec_balance_amount = value;
				}
			}
		}
	}
	
	public partial class getinvoicedetailsbyinvoiceidResult
	{
		
		private string _vc_invoice_number;
		
		private string _vc_manual_invoice_number;
		
		private string _vc_purchase_order_number;
		
		private string _vc_description;
		
		private string _vc_google_drive_file_id;
		
		private string _vc_invoice_access_link;
		
		private System.Nullable<decimal> _dec_HST_percent;
		
		private string _vc_invoice_status;
		
		private long _int_quote_id;
		
		private System.Nullable<long> _int_contact_id;
		
		private decimal _dec_invoice_total;
		
		private System.Nullable<decimal> _dec_balance_amount;
		
		private string _contact_name;
		
		private string _client_name;
		
		private string _created_by;
		
		private string _vc_send_to_email;
		
		private string _vc_project_manager_email;
		
		private string _vc_financial_email;
		
		private long _int_created_by_id;
		
		private System.DateTime _dt_created_date;
		
		private string _projectNumber;
		
		public getinvoicedetailsbyinvoiceidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_number", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string vc_invoice_number
		{
			get
			{
				return this._vc_invoice_number;
			}
			set
			{
				if ((this._vc_invoice_number != value))
				{
					this._vc_invoice_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_manual_invoice_number", DbType="VarChar(25)")]
		public string vc_manual_invoice_number
		{
			get
			{
				return this._vc_manual_invoice_number;
			}
			set
			{
				if ((this._vc_manual_invoice_number != value))
				{
					this._vc_manual_invoice_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_purchase_order_number", DbType="VarChar(25)")]
		public string vc_purchase_order_number
		{
			get
			{
				return this._vc_purchase_order_number;
			}
			set
			{
				if ((this._vc_purchase_order_number != value))
				{
					this._vc_purchase_order_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_description", DbType="VarChar(1000)")]
		public string vc_description
		{
			get
			{
				return this._vc_description;
			}
			set
			{
				if ((this._vc_description != value))
				{
					this._vc_description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_google_drive_file_id", DbType="VarChar(MAX)")]
		public string vc_google_drive_file_id
		{
			get
			{
				return this._vc_google_drive_file_id;
			}
			set
			{
				if ((this._vc_google_drive_file_id != value))
				{
					this._vc_google_drive_file_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_access_link", DbType="VarChar(MAX)")]
		public string vc_invoice_access_link
		{
			get
			{
				return this._vc_invoice_access_link;
			}
			set
			{
				if ((this._vc_invoice_access_link != value))
				{
					this._vc_invoice_access_link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_HST_percent", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> dec_HST_percent
		{
			get
			{
				return this._dec_HST_percent;
			}
			set
			{
				if ((this._dec_HST_percent != value))
				{
					this._dec_HST_percent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_invoice_status", DbType="VarChar(100)")]
		public string vc_invoice_status
		{
			get
			{
				return this._vc_invoice_status;
			}
			set
			{
				if ((this._vc_invoice_status != value))
				{
					this._vc_invoice_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_quote_id", DbType="BigInt NOT NULL")]
		public long int_quote_id
		{
			get
			{
				return this._int_quote_id;
			}
			set
			{
				if ((this._int_quote_id != value))
				{
					this._int_quote_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_contact_id", DbType="BigInt")]
		public System.Nullable<long> int_contact_id
		{
			get
			{
				return this._int_contact_id;
			}
			set
			{
				if ((this._int_contact_id != value))
				{
					this._int_contact_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_invoice_total", DbType="Decimal(15,2) NOT NULL")]
		public decimal dec_invoice_total
		{
			get
			{
				return this._dec_invoice_total;
			}
			set
			{
				if ((this._dec_invoice_total != value))
				{
					this._dec_invoice_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dec_balance_amount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> dec_balance_amount
		{
			get
			{
				return this._dec_balance_amount;
			}
			set
			{
				if ((this._dec_balance_amount != value))
				{
					this._dec_balance_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_name", DbType="VarChar(100)")]
		public string contact_name
		{
			get
			{
				return this._contact_name;
			}
			set
			{
				if ((this._contact_name != value))
				{
					this._contact_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_name", DbType="VarChar(100)")]
		public string client_name
		{
			get
			{
				return this._client_name;
			}
			set
			{
				if ((this._client_name != value))
				{
					this._client_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(201)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this._created_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_send_to_email", DbType="VarChar(100)")]
		public string vc_send_to_email
		{
			get
			{
				return this._vc_send_to_email;
			}
			set
			{
				if ((this._vc_send_to_email != value))
				{
					this._vc_send_to_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_project_manager_email", DbType="NVarChar(200)")]
		public string vc_project_manager_email
		{
			get
			{
				return this._vc_project_manager_email;
			}
			set
			{
				if ((this._vc_project_manager_email != value))
				{
					this._vc_project_manager_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vc_financial_email", DbType="VarChar(250)")]
		public string vc_financial_email
		{
			get
			{
				return this._vc_financial_email;
			}
			set
			{
				if ((this._vc_financial_email != value))
				{
					this._vc_financial_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_created_by_id", DbType="BigInt NOT NULL")]
		public long int_created_by_id
		{
			get
			{
				return this._int_created_by_id;
			}
			set
			{
				if ((this._int_created_by_id != value))
				{
					this._int_created_by_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_created_date", DbType="DateTime NOT NULL")]
		public System.DateTime dt_created_date
		{
			get
			{
				return this._dt_created_date;
			}
			set
			{
				if ((this._dt_created_date != value))
				{
					this._dt_created_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectNumber", DbType="VarChar(100)")]
		public string projectNumber
		{
			get
			{
				return this._projectNumber;
			}
			set
			{
				if ((this._projectNumber != value))
				{
					this._projectNumber = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
